FROM apache/superset

ENV SUPERSET_LOAD_EXAMPLES=no
ENV SUPERSET_SECRET_KEY=thisISaSECRET_1234
ENV SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@postgredb:5432/encuesta

# Copiar el script de inicialización y el dashboard exportado
COPY docker-init.sh /tmp/docker-init.sh
COPY superset-exports/dashboard.zip /tmp/dashboard.zip

ENTRYPOINT ["/bin/bash", "/docker-init.sh"]
