version: '3'

services:
  apppruebasunitarias:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - 5001:5001

    command: poetry run python3 pruebas.py
  
  apppruebasintegracion:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - 5002:5002

    command: poetry run pytest pruebasIntegracion.py
