version: '3.8'

services:
  # app
  app-spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
    restart: always
    environment:
      KAFKA_BROKER_SPARK: kafka:29092
      KAFKA_TOPIC_SPARK_RESPONSES: sparkResponses
      KAFKA_TOPIC_SPARK_SURVEYS: sparkSurveys

      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    ports:
      - 5001:5001
    networks:
      - web
    depends_on:
      - spark-master
    volumes:
      - .:/opt/app
    
    command: poetry run python3 spark.py

  # spark

  spark-master:
    image: bitnami/spark:3.5.1
    restart: always
    environment:
      - SPARK_MODE=master
    ports:
      - 7077:7077
      - 8080:8080
    networks:
      - web

  spark-worker-a:
    image: bitnami/spark:3.5.1
    restart: always
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - web
    depends_on:
      - spark-master

networks:
  web:
    driver: bridge