version: '3'

services:
  app:
    build: .
    restart: always
    environment:
      POSTGRES_DB_USER: postgres
      POSTGRES_DB_PASSWORD: postgres
      POSTGRES_DB_NAME: encuesta
      POSTGRES_DB_HOST: postgredb
      POSTGRES_DB_PORT: 5432

      # MONGODB_USER: root
      # MONGODB_PASSWORD: rootpassword

      # REDIS_HOST: redis
      # REDIS_PORT: 6379
      # REDIS_PASSWORD: redis
    ports:
      - 5000:5000
    
    networks:
      - web

    depends_on:
      - postgredb
      # - mongo
      # - redis


    volumes:
      - .:/opt/app

    command: poetry run python3 -m flask --app app.py --debug run --host=0.0.0.0

  postgredb:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - web

    environment:
      POSTGRES_PASSWORD: postgres
    
    volumes:
      - ./database/postgre/:/docker-entrypoint-initdb.d/
  
  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"

  #   networks:
  #     - web
    
  #   environment:
  #     MONGODB_USER: root
  #     MONGODB_PASSWORD: rootpassword

  # redis:
  #   image: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"

  #   networks:
  #     - web

networks:
  web:
    driver: bridge